name: EarlyAccess

on:
  push:
    branches: [ main ]

jobs:
  precheck:
    if: github.repository == 'jtama/project-graph-generator' && startsWith(github.event.head_commit.message, 'ðŸ Releasing version') != true && startsWith(github.event.head_commit.message, 'â¬†ï¸  Next version') != true
    runs-on: ubuntu-latest
    outputs:
      PROJECT_VERSION: ${{ steps.version.outputs.PROJECT_VERSION }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        id: version
        shell: bash
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$(echo $version)" >>$GITHUB_OUTPUT

  # Build native executable per runner
  build:
    runs-on: ubuntu-latest
    needs: [ precheck ]
    if: endsWith(${{ needs.precheck.outputs.PROJECT_VERSION }}, '-SNAPSHOT')
    name: 'Build artefacts'
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - name: 'Build artefacts'
        run: mvn -B -P release clean deploy
      - name: Deploy to Central
        uses: jreleaser/release-action@v2
        with:
          version: latest
          arguments: 'full-release'
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_NEXUS2_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.PROJECT_VERSION }}
          JRELEASER_OVERWRITE: true
          JRELEASER_DRAFT: true

        # Persist logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: jreleaser-logs
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties